spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    # mapper文件的位置
  type-aliases-package: com.example.demo.entity     # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true              # 开启驼峰映射
logging:
  level:
    com.example.demo.dao : debug                    # 打印sql语句日志